### ISSUE TITLE
Naive pip install from source failed on linux

### ISSUE THREAD

**Issue by mwilensky768** [PolyChord/PolyChordLite#99]
Hello,

I downloaded the source code from GitHub and called `pip install .` with `openmpi` loaded (gnu compiler) and the output was like so:

```
Processing /cosma/home/dp270/dc-wile1/repos/PolyChordLite
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /cosma/home/dp270/dc-wile1/.conda/envs/hera/lib/python3.9/site-packages (from pypolychord==1.20.2) (1.25.0)
Requirement already satisfied: scipy in /cosma/home/dp270/dc-wile1/.conda/envs/hera/lib/python3.9/site-packages (from pypolychord==1.20.2) (1.11.0)
Building wheels for collected packages: pypolychord
  Building wheel for pypolychord (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pypolychord (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [57 lines of output]
      running bdist_wheel
      running build
      running build_py
      make -C /cosma/home/dp270/dc-wile1/repos/PolyChordLite/src/polychord /cosma/home/dp270/dc-wile1/repos/PolyChordLite/lib/libchord.so
      make[1]: Entering directory `/cosma/home/dp270/dc-wile1/repos/PolyChordLite/src/polychord'
      /cosma/local/gcc/7.3.0/bin/gfortran -ffree-line-length-none -cpp -fPIC -fno-stack-arrays  -Ofast -DMPI -c nelder_mead.f90
      /cosma/local/gcc/7.3.0/bin/gfortran -ffree-line-length-none -cpp -fPIC -fno-stack-arrays  -Ofast -DMPI -c utils.F90
      utils.F90:5: Error: Can't open included file 'mpif.h'
      make[1]: *** [utils.o] Error 1
      make[1]: Leaving directory `/cosma/home/dp270/dc-wile1/repos/PolyChordLite/src/polychord'
      make: *** [/cosma/home/dp270/dc-wile1/repos/PolyChordLite/lib/libchord.so] Error 2
      Traceback (most recent call last):
        File "/cosma/home/dp270/dc-wile1/.conda/envs/hera/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/cosma/home/dp270/dc-wile1/.conda/envs/hera/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/cosma/home/dp270/dc-wile1/.conda/envs/hera/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-t6ug2wnl/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-t6ug2wnl/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-t6ug2wnl/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 125, in <module>
        File "/tmp/pip-build-env-t6ug2wnl/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-t6ug2wnl/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-t6ug2wnl/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-t6ug2wnl/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-t6ug2wnl/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-t6ug2wnl/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-t6ug2wnl/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 346, in run
          self.run_command("build")
        File "/tmp/pip-build-env-t6ug2wnl/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-t6ug2wnl/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-t6ug2wnl/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-t6ug2wnl/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-t6ug2wnl/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-t6ug2wnl/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-t6ug2wnl/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 97, in run
        File "/cosma/home/dp270/dc-wile1/.conda/envs/hera/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['make', '-e', 'libchord.so']' returned non-zero exit status 2.
      [end of output]
```

To solve this, @williamjameshandley instructed me to first, from a clean source directory, call `make`, and then `pip install .`. This reported a successful install, and the example script ran correctly. It would probably be good to include these instructions in the readme so that other users know of it as a potential solution to installation problems.

**Comment by Christian554** [comment]
After a long time, I managed to install this package, through using "make" before "pip install . ".
Please, include it in the docs, so that people don't waste days.

**Comment by htjb** [comment]
Can you add this to the instructions for python install in the README please?
